### PR TITLE
Stefan/segment

### PR DESCRIPTION
**Pull request by stefanceriu**

### CODE REVIEW

**Comment by fredrikbonander** [comment]
Good job

**Comment by stefanceriu** [comment]
x6ljovv

**Comment by andrezero** [comment]
https://www.mememaker.net/api/bucket?path=static/img/memes/full/2017/May/27/16/well-done-now-clap.jpg

**Comment by andrezero** [comment]
clap

**Comment by sathran** [comment]
It's a very nice!

**Comment by stefanceriu** [comment]
ezgif-2-a8aee127ed8d

**Pull request merged**
